title: GC
author:
  email: hi@greatcouncil.club
description: > # this means to ignore newlines until "show_excerpts:"
  Vulgarization website from the Great Council authority for a proper usage of slack in the company.
header_logo: android-chrome-192x192.png  

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # social_links:
  #  twitter: jekyllrb
  #  github:  jekyll

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

algolia:
   application_id: K3412NKPE1
   files_to_exclude:
      - wall_of_shame.md
      - search.md
      - index.md
      - _emojis/mole.md
      - gotchas.md

   index_name: emojis
   search_only_api_key: 1ea751f5c1ff3b25f9b53ac518666c7e
   settings:
    customRanking:                                                               
      - asc(title) 
    searchableAttributes:
      - title
      - unordered(content)
      - tags
      - text
      - img
      - alias
    attributesToHighlight:                                                       
      - categories                                                               
      - collection                                                               
      - content                                                                  
      - headings                                                                 
      - html                                                                     
      - img                                                                      
      - tags                                                                     

collections:
    emojis:
      output: true
      permalink: /define/:path/
